#
###################################
# Site wide configuration
####################################
#
title: Jimmy Li
email: jimmyli2002@gmail.com
description: My personal blog
url: "https://blog.jimmyli.us"
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jimmy Li
  avatar: pattern-profile.jpg
  job: ""
  bio: "Web Developer, CTFs with redpwn and dicegang"
  email: jimmyli2002@gmail.com
  disqus-shortname:
  twitter: jimfutsu
  facebook: #username
  google:
    plus: #username
    analytics: UA-154870924-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jimmyl02
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
