# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## => Site Settings
##############################
text_skin:        september    # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme:  default    # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: "https://gabrielfok.us" 
baseurl: / 
title:            Gabriel Fok
description: >             


## => Language and Timezone
##############################
lang:     en                    
timezone: America/Los_Angeles  

## => Author and Social
##############################
author:
  name:     Gabriel Fok
  avatar:   assets/images/logo.png
  job:      ""
  bio:      "Technology, Cybersecurity, and Competition"
  email:    gabrielfok128@gmail.com
  twitter:  baseq_twt
  github:   dbaseqp
  gitlab: #username
  linkedin: gabriel-fok
  instagram: #username
  lastfm: #username
  
## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository:       dbaseqp/blog
repository_tree:  master

## => Paths
##############################
paths:
  root: # title link url, "/" (default)
  home: /blog/ # home layout url, "/" (default)
  archive: # "/archive.html" (default)
  rss: # "/feed.xml" (default)

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true

## => Paginate
##############################
paginate: 8
paginate_path: /blog/page:num # don't change this unless for special need

## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID: # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository: # GitHub repo
    owner: # GitHub repo owner
    admin:  # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id: # LeanCloud App id
    app_key: # LeanCloud App key
    placeholder: # Prompt information
    visitor: # false (default)
    meta: # "[nick, mail, link]" (default) nickname, E-mail, Personal-site

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id: # LeanCloud App id
    app_key: # LeanCloud App key
    app_class: # LeanCloud App class

## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id: # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: /articles/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: false
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
